import { NgModule } from '@angular/core';

import {
    MatButtonModule,
    MatIconModule,
    MatListModule,
    MatTooltipModule,
    MatTabsModule,
    MatMenuModule,
    MatCheckboxModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatTableModule,
    MatBottomSheetModule,
    MatSnackBarModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatGridListModule,
    MatToolbarModule,
    MatProgressBarModule,
    MatPaginatorModule,
    MatRadioModule,
    MatSortModule,
    MatCardModule,
    MatStepperModule,
    MatSlideToggleModule,
    MatButtonToggleModule,
} from '@angular/material';
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
import { DragDropModule } from '@angular/cdk/drag-drop';

@NgModule({
    imports: [
        // Material
        MatButtonModule,
        MatIconModule,
        MatListModule,
        MatTooltipModule,
        MatTabsModule,
        MatMenuModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTableModule,
        MatBottomSheetModule,
        MatSnackBarModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatGridListModule,
        MatToolbarModule,
        MatProgressBarModule,
        MatPaginatorModule,
        MatRadioModule,
        NgxMatSelectSearchModule,
        MatSortModule,
        MatCardModule,
        MatStepperModule,
        MatSlideToggleModule,
        DragDropModule,
        MatButtonToggleModule
    ],
    exports: [
        // Material
        MatButtonModule,
        MatIconModule,
        MatListModule,
        MatTooltipModule,
        MatTabsModule,
        MatMenuModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatSelectModule,
        MatTableModule,
        MatBottomSheetModule,
        MatSnackBarModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatGridListModule,
        MatToolbarModule,
        MatProgressBarModule,
        MatPaginatorModule,
        MatRadioModule,
        NgxMatSelectSearchModule,
        MatSortModule,
        MatCardModule,
        MatStepperModule,
        MatSlideToggleModule,
        DragDropModule,
        MatButtonToggleModule
    ]
})
export class SharedMaterialModule { }
